apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc-rwo
  labels:
    app: mysql
    tier: db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi