apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-mysql
    tier: db
  name: mysql-hls
spec:
  #clusterIP: ClusterIP
  clusterIP: None
  ports:
    - port: 3306
  selector:
    app: mysql-sfs
    tier: db