apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc-rwx
  labels:
    app: wordpress
    tier: frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi