apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress:4.8-apache
        name: wordpress
        envFrom:
        - secretRef:
            name: wp-connection
        - configMapRef:
            name: wp-cm-vars
        ports:
        - containerPort: 80
          name: wordpress
#        volumeMounts:
#        - name: html
#          mountPath: /var/www/html
      volumes:
      - name: html
        persistentVolumeClaim:
          claimName: wp-pvc-rwx        